// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $npm_path_ from "./routes/npm/[...path].ts";
import * as $pages_01_static from "./routes/pages/01-static.tsx";
import * as $pages_02_postcss_route from "./routes/pages/02-postcss-route.tsx";
import * as $pages_03_postcss_jit_route from "./routes/pages/03-postcss-jit-route.tsx";
import * as $pages_04_dynamic_at_startup from "./routes/pages/04-dynamic-at-startup.tsx";
import * as $postcss_jit_path_ from "./routes/postcss-jit/[...path].ts";
import * as $postcss_path_ from "./routes/postcss/[...path].ts";
import * as $Counter from "./islands/Counter.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/npm/[...path].ts": $npm_path_,
    "./routes/pages/01-static.tsx": $pages_01_static,
    "./routes/pages/02-postcss-route.tsx": $pages_02_postcss_route,
    "./routes/pages/03-postcss-jit-route.tsx": $pages_03_postcss_jit_route,
    "./routes/pages/04-dynamic-at-startup.tsx": $pages_04_dynamic_at_startup,
    "./routes/postcss-jit/[...path].ts": $postcss_jit_path_,
    "./routes/postcss/[...path].ts": $postcss_path_,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
